import React from 'react'

import './lib/AntdRegistry'

import './globals.css'

export const metadata = {
  title: 'Life-study of the Bible with Witness Lee, Radio Broadcast of Living Stream Ministry',
  description: 'Generated by Lois',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  )
}
